### ISSUE TITLE
Running from the command line causes an invalid response

### ISSUE THREAD

**Issue by gavinwilliams** [liuggio/RackspaceCloudFilesBundle#5]
We're using this bundle to upload files to Rackspace after running a job through the command line. After several hours, we consistently get an Invalid Response Exception. Restarting the command seems to fix it. Any ideas?

**Comment by gavinwilliams** [comment]
Seems as though if you run it for a long time, the authentication token will expire. Is there any way of authenticating again through the bundle?

**Comment by liuggio** [comment]
Hi,
thanks for reporting,
are you talking about  `AssetsInstallCommand`?
@benjamindulau do you have any idea?

There's no way of re-authenticate with the service in this bundle, and I didn't find any option of Rackspace API to extend the timeout.

**Comment by gavinwilliams** [comment]
No, just if you upload files to rackspace using a custom command line script.

Will

``` php
$rackspace = $this->getContainer()->get('liuggio_rackspace_cloud_files.service');
        $rackspace->getAuthentication()->authenticate();
        $conn = $rackspace->getConnection();
        $container = $conn->get_container($container);
```

not do it?

**Comment by liuggio** [comment]
mm I don't think it could works.

**Comment by liuggio** [comment]
the api are totally chanced. closed
