### ISSUE TITLE
Replace php-cloud api with https://github.com/rackspace/php-opencloud

### ISSUE THREAD

**Issue by liuggio** [liuggio/RackspaceCloudFilesBundle#6]
Cool task :+1: 

php-cloudfiles is deprecated and will be unavailable after August 1, 2013. Please visit the php-opencloud repository for its replacement

anyone wants help?

**Comment by lmammino** [comment]
Should use tags in this repo to allow people to still use the old version (with php-cloudfiles) through composer

**Comment by liuggio** [comment]
Ehm is done by default, is not possible to use it because rackspace deleted the old repo and the API are not accessible :-1:

**Comment by lmammino** [comment]
Damn.. didn't noticed it... luckily i have a fork of the original rackspace cloud files api repository and can still use it before focusing on the migration to open cloud.
Thanks anyway for the (really) quick reply ;)
