### ISSUE TITLE
Region is hard corded, and you cannot modify it for other regions

### ISSUE THREAD

**Issue by ghost** [liuggio/RackspaceCloudFilesBundle#9]
I have a cloud files CDN instance in Rackspaces' DFW data center... Before the change to use php-opencloud I had no trouble deploying to my cdn using this bundle... Afterwards my app was not able to connect to the CDN to deploy changes.  I had to create a compiler pass in my bundle, and replace to rackspace_api class with one that overwrote the connection method, and allowed me to change the default region for the cloud files key.  I would think this should be in the package configuration, however; that configuration value is unrecognized.

**Comment by liuggio** [comment]
@toretto460 please could you go deeper?

**Comment by ghost** [comment]
In the class Liuggio\RackspaceCloudFilesBundle\Service\RackspaceApi The member $region is marked as private, it is also hardcoded to 'LON'.  There is no way to change the region by configuration value, so when trying to write content to a cloud files region such as ORD, or DFW you get connection errors.  To fix it I had to subclass the Rackspace API, using a compiler pass to override the bundles rackspace api class. I then overrode the public connect method in my class, and in that function I called set defaults for the ObjectStore and set the region to DFW which is where my cloudfiles happens to be living.

I felt it should have been a configurable key under liuggio_rackspace_cloud_files namespace.  At this point all I can do is report the issue, but perhaps tonight I can create a pull request that would make the region a configurable value.

**Comment by liuggio** [comment]
totally agree with you! 
:+1: awesome!!!

**Comment by ghost** [comment]
Since pull request #10 Solved this issue, I'll close it as well.
